export const gtypes = {
    TASKS: "TASKS",
    SELECTED_INDEXES: "SELECTED_INDEXES",

    DRAGGED_INDEX: "DRAGGED_INDEX",
    CONTAINER_TOP: "CONTAINER_TOP",
    CONTAINER_HEIGHT: "CONTAINER_HEIGHT",

    MODAL_SHOWED: "MODAL_SHOWED",
    MODAL_TYPE: "MODAL_TYPE",
    MODAL_TASK_INDEX: "MODAL_TASK_INDEX",

    NOTIFICATIONS: "NOTIFICATIONS",
};

export const atypes = {
    TRY_LOAD_TASKS: "TRY_LOAD_TASKS",
    SAVE_TASKS: "SAVE_TASKS",
    SET_DEFAULT_TASKS: "SET_DEFAULT_TASKS",
    REMOVE_TASK: "REMOVE_TASK",
    REMOVE_SELECTED_TASKS: "REMOVE_SELECTED_TASKS",
    CHANGE_ORDER: "CHANGE_ORDER",
    TRY_SET_TASK: "TRY_SET_TASK",
    SET_CHECKED_STATE: "SET_CHECKED_STATE",
    TOGGLE_TASK_SELECTION: "TOGGLE_TASK_SELECTION",

    SET_DRAGGED_INDEX: "SET_DRAGGED_INDEX",
    CHANGE_DRAGGED_INDEX: "CHANGE_DRAGGED_INDEX",
    SET_CONTAINER_TOP: "SET_CONTAINER_TOP",

    SHOW_MODAL: "SHOW_MODAL",
    HIDE_MODAL: "HIDE_MODAL",

    PUSH_NOTIFICATION: "PUSH_NOTIFICATION",
};
